### ISSUE TITLE
- c_structs (0): "return"

### ISSUE THREAD

**Issue by FatalBulletHit** [bnnm/wwiser-utils#1]
If I'm not mistaken, line 127 and 132 of [wwise_pck_extractor.bms cause](https://github.com/bnnm/wwiser-utils/blob/master/scripts/wwise_pck_extractor.bms) cause a `- c_structs (0): "return"` error as `return` doesn't exist in the bms syntax.

**Comment by bnnm** [comment]
It does work for me (returns from function and continues normally) with a not-too-recent version of quickbms. I can't find references to that feature though in the readme, so maybe one is not supposed to use it. Workarounds make code ugly tho.

**Comment by FatalBulletHit** [comment]
Oh, I should've made it more clear, the script runs w/o any issues, but I thought I'd let you know.

**Comment by bnnm** [comment]
Warning should be fixed now
