### ISSUE TITLE
How to find the original file name of the wem file of total war roma 2?

### ISSUE THREAD

**Issue by darkness-A** [bnnm/wwiser-utils#10]
![image](https://user-images.githubusercontent.com/22480057/194452378-2ee0323a-c1b6-4448-8afc-b4ba7a9cdfde.png)
![image](https://user-images.githubusercontent.com/22480057/194452399-b9932453-fd3d-461e-b43c-c5df0ade1a82.png)

**Comment by bnnm** [comment]
It is not possible to get original filenames from .wem numbers.

You can sometimes reverse .bnk event names though, that is explained [here](https://github.com/bnnm/wwiser/blob/master/doc/WWISER.md#wwise-files-and-names) and [here](https://github.com/bnnm/wwiser-utils/blob/master/doc/NAMES.md).
